import Shopheader from "@/components/shopheader";

import { Inter } from "next/font/google";
import HeroDiv from "@/components/HeroDiv";
import Category from "@/components/Category";
import AllProduct from "@/components/AllProduct";
import Fotter from "@/components/Fotter";
import StoreProvider from "@/components/storeProvider";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <>
      <Shopheader />
      {children}
       <Fotter />
    </>
  );
}
